#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.127                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC =  -IC:\wxWidgets-2.9.2\include -IC:\wxWidgets-2.9.2\contrib\include
CFLAGS =  -pipe -mthreads -D__GNUWIN32__ -D__WXMSW__ -DWXUSINGDLL -DwxUSE_UNICODE [[if (PLATFORM == PLATFORM_MSW && (GetCompilerFactory().GetCompilerVersionString(_T("gcc")) >= _T("4.0.0"))) print(_T("-Wno-attributes"));]] -Winvalid-pch -include wx_pch.h -DWX_PRECOMP -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS =  -mthreads

INC_RELEASE =  $(INC) -IC:\wxWidgets-2.9.2\lib\gcc_dll\mswu -Ilib\ -Isrc\ -Ires\
CFLAGS_RELEASE =  $(CFLAGS) -O2
RESINC_RELEASE =  $(RESINC) -IC:\wxWidgets-2.9.2\lib\gcc_dll\mswu
RCFLAGS_RELEASE =  $(RCFLAGS)
LIBDIR_RELEASE =  $(LIBDIR) -LC:\wxWidgets-2.9.2\lib\gcc_dll
LIB_RELEASE = $(LIB) libwxmsw29u.a
LDFLAGS_RELEASE =  -s $(LDFLAGS)
OBJDIR_RELEASE = \.objs
DEP_RELEASE = 
OUT_RELEASE = Orb.exe

OBJ_RELEASE = $(OBJDIR_RELEASE)\res\resource.o $(OBJDIR_RELEASE)\src\SolarSystem.o $(OBJDIR_RELEASE)\src\Planet.o $(OBJDIR_RELEASE)\src\OrbMain.o $(OBJDIR_RELEASE)\src\OrbApp.o $(OBJDIR_RELEASE)\src\NewPlanetDialog.o $(OBJDIR_RELEASE)\src\HelpDialog.o $(OBJDIR_RELEASE)\src\GraphPane.o $(OBJDIR_RELEASE)\src\ChangeFrameDialog.o $(OBJDIR_RELEASE)\src\BenchmarkDialog.o

all: release

clean: clean_release

before_release: 
	cmd /c if not exist $(OBJDIR_RELEASE)\res md $(OBJDIR_RELEASE)\res
	cmd /c if not exist $(OBJDIR_RELEASE)\src md $(OBJDIR_RELEASE)\src

after_release: 

release: before_release out_release after_release

out_release: $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LDFLAGS_RELEASE) $(LIBDIR_RELEASE) $(OBJ_RELEASE) $(LIB_RELEASE) -o $(OUT_RELEASE)

$(OBJDIR_RELEASE)\res\resource.o: res\resource.rc
	$(WINDRES) -i res\resource.rc -J rc -o $(OBJDIR_RELEASE)res\resource.o -O coff $(INC_RELEASE)

$(OBJDIR_RELEASE)\src\SolarSystem.o: src\SolarSystem.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\SolarSystem.cpp -o $(OBJDIR_RELEASE)\src\SolarSystem.o

$(OBJDIR_RELEASE)\src\Planet.o: src\Planet.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\Planet.cpp -o $(OBJDIR_RELEASE)\src\Planet.o

$(OBJDIR_RELEASE)\src\OrbMain.o: src\OrbMain.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\OrbMain.cpp -o $(OBJDIR_RELEASE)\src\OrbMain.o

$(OBJDIR_RELEASE)\src\OrbApp.o: src\OrbApp.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\OrbApp.cpp -o $(OBJDIR_RELEASE)\src\OrbApp.o

$(OBJDIR_RELEASE)\src\NewPlanetDialog.o: src\NewPlanetDialog.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\NewPlanetDialog.cpp -o $(OBJDIR_RELEASE)\src\NewPlanetDialog.o

$(OBJDIR_RELEASE)\src\HelpDialog.o: src\HelpDialog.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\HelpDialog.cpp -o $(OBJDIR_RELEASE)\src\HelpDialog.o

$(OBJDIR_RELEASE)\src\GraphPane.o: src\GraphPane.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\GraphPane.cpp -o $(OBJDIR_RELEASE)\src\GraphPane.o

$(OBJDIR_RELEASE)\src\ChangeFrameDialog.o: src\ChangeFrameDialog.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\ChangeFrameDialog.cpp -o $(OBJDIR_RELEASE)\src\ChangeFrameDialog.o

$(OBJDIR_RELEASE)\src\BenchmarkDialog.o: src\BenchmarkDialog.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\BenchmarkDialog.cpp -o $(OBJDIR_RELEASE)\src\BenchmarkDialog.o

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd $(OBJDIR_RELEASE)\res
	cmd /c rd $(OBJDIR_RELEASE)\src

.PHONY: before_release after_release clean_release

.PHONY: tarball

tarball: 
	


